### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory for configuration path 

### ISSUE THREAD

**Issue by oshholail** [CarnoZhao/RSIPAC_Track2#1]
File "solver.py", line 73, in <module>
    cfg = OmegaConf.load(cfg)
 File "C:\Users\Anaconda3\envs\RS\lib\site-packages\omegaconf\omegaconf.py", line 187, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:

what is the problem for path config ?

**Comment by CarnoZhao** [comment]
I think this is a bug of omegaconf on windows.

**Comment by oshholail** [comment]
how can i solve it ?

**Comment by CarnoZhao** [comment]
I'm sure the bug is not related with the key point of this repo. So I suggest you:

1. make sure your config path is correct
2. search the error info on internet

**Comment by oshholail** [comment]
thank you for quick reply , i will search for this

**Comment by oshholail** [comment]
solved many thanks
