### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\RSIPAC_Track2-rsipac\\c'

### ISSUE THREAD

**Issue by 953951975** [CarnoZhao/RSIPAC_Track2#3]
您好，运行solver.py的时候出现了以下问题 
Traceback (most recent call last):
  File "D:/RSIPAC_Track2-rsipac/Solver.py", line 74, in <module>
    cfg = OmegaConf.load(cfg)
  File "D:\anaconda3\envs\deepl\lib\site-packages\omegaconf\omegaconf.py", line 187, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\RSIPAC_Track2-rsipac\\c'

然后我尝试debug的时候发现cfg=c
而且在solver的第四行中parser.add_argument("--config", dest = "config", default = "config.yaml", type = str, nargs = "+")
项目中好像没有config.yaml文件，这个要怎么解决呢，或者要做什么修改采用其他的yaml吗

**Comment by CarnoZhao** [comment]
baseline的config在./configs/base.yaml，其他config可以自己参考base构建

和windows文件路径读取的相关问题和本项目无关，可以自行搜索解决办法

**Comment by 953951975** [comment]
好的，那如果要采用base.yaml,需要对哪些参数和路劲进行修改呢

**Comment by CarnoZhao** [comment]
python Solver.py --config ./configs/base.yaml --gpus 0

**Comment by 953951975** [comment]
好的，谢谢啦
